### ISSUE TITLE
Make font color light for dark theme

### ISSUE THREAD

**Issue by vitaliy-bobrov** [bfmatei/stencil-inspector#1]
**Version:**
```
 @bfmatei/stencil-inspector@1.0.0
```

**I'm submitting a:**
- [ x] bug report
- [ ] feature request
- [ ] support request

**Current Behavior:**
Text is black on chrome dark theme selected

**Expected Behavior:**
Text should be white

**Steps to Reproduce:**
1. Set dark theme in Chrome
2. Open Stencil inspector

**Related Code:**
Styles

**Comment by bfmatei** [comment]
Thanks!

This is fixed in v1.0.1 (currently in testing).

**Comment by vitaliy-bobrov** [comment]
I wanted to fix myself(((

**Comment by bfmatei** [comment]
Issue was solved
