### ISSUE TITLE
Add free CI for builds

### ISSUE THREAD

**Issue by vitaliy-bobrov** [bfmatei/stencil-inspector#2]
We could add Travis or Circle CI to automatically run builds.

**Comment by vitaliy-bobrov** [comment]
@bfmatei, your thoughts about Travis CI builds? I can provide basic config

**Comment by bfmatei** [comment]
I would go for CircleCI. It has some very powerful features in with the 2nd version of the schema. Also you can define workflows for better handling of the processes.

We can use it to continuously deploy the extension in Chrome Web Store also :)

**Comment by bfmatei** [comment]
I implemented CircleCI with auto-publish to Chrome Web Store
