### ISSUE TITLE
It only shows the inspector, if I run Stencil on localhost

### ISSUE THREAD

**Issue by mortenmoulder** [bfmatei/stencil-inspector#4]
**Version:**

```
 @bfmatei/stencil-inspector@1.0.1 (latest from the webstore)
```

**I'm submitting a:**

- [X] bug report

**Current Behavior:**

When I include Stencil in my ASP.NET application, it does not show the inspector in the inspection pane. It does when I run it using localhost with `npm start` though. 

Reason for not running Stencil using `npm start` : CORS with our other running project.

**Expected Behavior:**

It should show the inspector in the inspection pane, if it detects Stencil is running.

**Steps to Reproduce:**

1.  Make a new ASP.NET MVC project
2. Place StencilJS within the folder and include the JS so it works (look at the example)
3. Check if the inspector shows up in the pane 

**Related Code:**
```
    @{
        ViewBag.Title = "Test component";
    }
    <script src="~/stencil/www/build/app.js"></script>
    <test-component name="Test"></test-component>
```

**Comment by bfmatei** [comment]
Hello @mortenmoulder!

Thanks for opening an issue. At the moment i refactored a part of the extension and it is under testing. The new version works for custom namespaces and production apps built with Stencil. Are you OK with cloning the `develop` branch and try the extension loaded from the disk instead of web store? You can find the instructions in the [README.md](https://github.com/bfmatei/stencil-inspector/blob/develop/README.md) file

**Comment by mortenmoulder** [comment]
@bfmatei Thanks for the quick reply!

I've done a checkout on the develop branch, and I've built it and imported it into Chrome now. I can now see the inspector in the pane, but when I click on it, I get an error:

>Requests to the server have been blocked by an extension

And then I get the dreadful icon:
![image](https://user-images.githubusercontent.com/1304665/36248969-8f837588-1239-11e8-817c-b2b6adb080b6.png)

**Comment by mortenmoulder** [comment]
I have tried adding `*://*/*` to the `permissions` property in `manifest.json`, but I still get the error.

**Comment by bfmatei** [comment]
It's weird that the extension is not making any HTTP calls, it just inspects the window object and the current selected element in the dev panel.

1. Are you running any adblockers? Can you disable them and retry? I personally tested with ublock origin and it doesn't block it.
2. Try removing the `content_security_policy` line from the `manifest.json` file.
3. Can you please try to run it on https://stencil-boilerplate.bmatei.com ? I just installed the extension on another machine and it inspects it perfectly.
4. What OS are you using?

**Comment by mortenmoulder** [comment]
@bfmatei I've updated my last post, and it appears to be working now.

![image](https://user-images.githubusercontent.com/1304665/36249544-5434ae64-123b-11e8-8d6c-ff89e1a51093.png)

However, I'm not sure if this behavior is normal.

**Comment by bfmatei** [comment]
I forgot something: Chrome is quite buggy when it comes to extensions. Sometimes you just need to click **Reload** a couple of times in the extensions page and then right click in the extension panel and hit **Reload frame**.

`Component is not connected` means that the current inspected element is not a Stencil component. **Context** and **Components** contain general data which is extracted from the `window` object while the rest are extracted from the current selected element.

Just to be sure that the extension works without any modifications:
1. Ensure the extension is untouched `git reset --hard HEAD`
2. `rm -rf dist/ www/`
3. `npm run build`
4. Chrome -> Extensions -> Remove Stencil Inspector
5. Load unpacked...
6. Reload
7. Right click in the extension panel -> reload frame.

I appreciate the effort a lot.

PS: Avoid using `npm run dev` when building the extension. Sometimes it doesn't rebuild as it should. It's best to edit a file and then trigger `npm run build` followed by the steps mentioned in the first paragraph.

**Comment by mortenmoulder** [comment]
Aaah now it works perfectly yes. Awesome stuff, dude! Thanks a lot.
